name: Sync Fork

on:
  push:
    branches: [ 'main' ]
  schedule:
    - cron: '0 */2 * * *' # every 2 hours
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: alist-org
          base: build
          head: main
          merge_method: rebase
